name: Generate a build and push to another branch

on:
  push:
    branches:
      - master # The branch name your are commit the new changes

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Setup PHP
      
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist
   
      - name: Install all dependencies
   
        run: npm install

      - name: Build
        run: npm run build # The build command of your project

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: master # The branch name where you want to push the assets
          FOLDER: public/build # The directory where your assets are generated
          TARGET_DIR: public_html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
         
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
         ssh-private-key: "${{ secrets.SSH_PRIVATE_KEY }}"
         ssh-passphrase: "${{ secrets.SSH_PASSPHRASE }}"

      - name: Create .env file on the server
        run: | 
            ssh -p 65002 u910876084@82.112.232.32 "cp /public_html/.env.example /public_html/.env && \
            echo 'APP_KEY=${{ secrets.APP_KEY }}' >> /public_html/.env"

            echo 'APP_NAME: ${{ vars.APP_NAME }} >> /public_html/.env"
            echo 'DEFAULT_CATEGORY_IMAGE: ${{ vars.DEFAULT_CATEGORY_IMAGE }}'  >> /public_html/.env"
            echo 'TOPICS_IMAGE: ${{ vars.TOPICS_IMAGE }}'  >> /public_html/.env"
            echo 'DEFAULT_CITY: ${{ vars.DEFAULT_CITY }}'  >> /public_html/.env"
            echo 'RANDOM_IMAGE_KEY: ${{ secrets.RANDOM_IMAGE_KEY}}' >> /public_html/.env"
            echo 'PINATA_SECRET_ACCESS_KEY: ${{ secrets.PINATA_SECRET_ACCESS_KEY }}'  >> /public_html/.env"
            echo 'DB_DATABASE: ${{ secrets.DB_DATABASE }}'  >> /public_html/.env"
            echo 'DB_USERNAME: ${{ secrets.DB_USERNAME }}'  >> /public_html/.env"
            echo 'DB_PASSWORD: ${{ secrets.DB_PASSWORD }}'  >> /public_html/.env"
            echo 'APP_DEBUG:  ${{ vars.APP_DEBUG }}'  >> /public_html/.env"

